'use client'

import Link from 'next/link'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Separator } from '@/components/ui/separator'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import type { DraftISMSScope } from '@/lib/agents/intake-agent'

interface DraftScopeReviewProps {
  draftScope: DraftISMSScope
  onApprove: () => void
  onEdit: () => void
  onRegenerate: () => void
  isApproving?: boolean
  readOnly?: boolean
  onUpdateResponses?: () => void
}

export function DraftScopeReview({
  draftScope,
  onApprove,
  onEdit,
  onRegenerate,
  isApproving = false,
  readOnly = false,
  onUpdateResponses,
}: DraftScopeReviewProps) {
  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <Alert>
        <AlertTitle>{readOnly ? 'Approved ISMS Scope' : 'Draft ISMS Scope - Review Required'}</AlertTitle>
        <AlertDescription>
          {readOnly
            ? 'This is your currently approved ISMS scope. You can update your responses or regenerate the scope at any time.'
            : 'This scope was generated by the Voyu AI agent based on your intake responses. Please review carefully before approving. This will become the foundation of your ISMS.'}
        </AlertDescription>
      </Alert>

      {/* Next Steps — shown after approval */}
      {readOnly && (
        <Card className="border-primary/30 bg-primary/5">
          <CardHeader>
            <CardTitle>Next Steps</CardTitle>
            <CardDescription>
              Your scope is approved. Continue building your ISMS by completing these phases in order.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="grid sm:grid-cols-3 gap-4">
              <Link href="/assets" className="block">
                <div className="rounded-lg border bg-background p-4 hover:border-primary/50 transition-colors h-full">
                  <div className="text-sm font-medium text-muted-foreground mb-1">Step 1</div>
                  <div className="font-semibold mb-1">Asset Register</div>
                  <p className="text-sm text-muted-foreground">
                    Document the information assets within your scope.
                  </p>
                </div>
              </Link>
              <Link href="/risks" className="block">
                <div className="rounded-lg border bg-background p-4 hover:border-primary/50 transition-colors h-full">
                  <div className="text-sm font-medium text-muted-foreground mb-1">Step 2</div>
                  <div className="font-semibold mb-1">Risk Assessment</div>
                  <p className="text-sm text-muted-foreground">
                    Identify threats, vulnerabilities, and treatment plans.
                  </p>
                </div>
              </Link>
              <Link href="/controls" className="block">
                <div className="rounded-lg border bg-background p-4 hover:border-primary/50 transition-colors h-full">
                  <div className="text-sm font-medium text-muted-foreground mb-1">Step 3</div>
                  <div className="font-semibold mb-1">Controls & Evidence</div>
                  <p className="text-sm text-muted-foreground">
                    Implement Annex A controls and collect supporting evidence.
                  </p>
                </div>
              </Link>
            </div>
            <div className="mt-4 flex justify-center">
              <Link href="/dashboard">
                <Button>Go to Dashboard</Button>
              </Link>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Scope Statement */}
      <Card>
        <CardHeader>
          <CardTitle>ISMS Scope Statement</CardTitle>
          <CardDescription>
            This statement defines what your Information Security Management System covers
          </CardDescription>
        </CardHeader>
        <CardContent>
          <p className="text-lg">{draftScope.scopeStatement}</p>
        </CardContent>
      </Card>

      {/* Boundaries */}
      <Card>
        <CardHeader>
          <CardTitle>Scope Boundaries</CardTitle>
          <CardDescription>
            Physical, logical, and organizational boundaries of your ISMS
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div>
            <h4 className="font-medium mb-2">Physical Boundaries</h4>
            <div className="flex flex-wrap gap-2">
              {draftScope.boundaries.physical.map((item, i) => (
                <Badge key={i} variant="secondary">{item}</Badge>
              ))}
            </div>
          </div>
          <Separator />
          <div>
            <h4 className="font-medium mb-2">Logical Boundaries</h4>
            <div className="flex flex-wrap gap-2">
              {draftScope.boundaries.logical.map((item, i) => (
                <Badge key={i} variant="secondary">{item}</Badge>
              ))}
            </div>
          </div>
          <Separator />
          <div>
            <h4 className="font-medium mb-2">Organizational Boundaries</h4>
            <div className="flex flex-wrap gap-2">
              {draftScope.boundaries.organizational.map((item, i) => (
                <Badge key={i} variant="secondary">{item}</Badge>
              ))}
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Exclusions */}
      {draftScope.exclusions.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle>Exclusions</CardTitle>
            <CardDescription>
              Items explicitly excluded from the ISMS scope (must be justified to auditors)
            </CardDescription>
          </CardHeader>
          <CardContent>
            <ul className="list-disc pl-5 space-y-1">
              {draftScope.exclusions.map((item, i) => (
                <li key={i}>{item}</li>
              ))}
            </ul>
          </CardContent>
        </Card>
      )}

      {/* Interested Parties */}
      <Card>
        <CardHeader>
          <CardTitle>Interested Parties</CardTitle>
          <CardDescription>
            Stakeholders with requirements relevant to your ISMS (ISO 27001 Clause 4.2)
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Party</TableHead>
                <TableHead>Type</TableHead>
                <TableHead>Expectations</TableHead>
                <TableHead>Requirements</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {draftScope.interestedParties.map((party, i) => (
                <TableRow key={i}>
                  <TableCell className="font-medium">{party.name}</TableCell>
                  <TableCell>
                    <Badge variant={party.type === 'internal' ? 'default' : 'outline'}>
                      {party.type}
                    </Badge>
                  </TableCell>
                  <TableCell>
                    <ul className="list-disc pl-4 text-sm">
                      {party.expectations.map((exp, j) => (
                        <li key={j}>{exp}</li>
                      ))}
                    </ul>
                  </TableCell>
                  <TableCell>
                    <ul className="list-disc pl-4 text-sm">
                      {party.requirements.map((req, j) => (
                        <li key={j}>{req}</li>
                      ))}
                    </ul>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>

      {/* Regulatory Requirements */}
      <Card>
        <CardHeader>
          <CardTitle>Regulatory & Legal Requirements</CardTitle>
          <CardDescription>
            Regulations that may apply to your organization (ISO 27001 Clause 4.2)
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Regulation</TableHead>
                <TableHead>Description</TableHead>
                <TableHead>Applicable?</TableHead>
                <TableHead>Reasoning</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {draftScope.regulatoryRequirements.map((reg, i) => (
                <TableRow key={i}>
                  <TableCell className="font-medium">{reg.regulation}</TableCell>
                  <TableCell className="text-sm">{reg.description}</TableCell>
                  <TableCell>
                    <Badge variant={reg.applicable ? 'default' : 'secondary'}>
                      {reg.applicable ? 'Yes' : 'No'}
                    </Badge>
                  </TableCell>
                  <TableCell className="text-sm">{reg.reasoning}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>

      {/* Annex A Assumptions */}
      <Card>
        <CardHeader>
          <CardTitle>Initial Annex A Control Assumptions</CardTitle>
          <CardDescription>
            Preliminary applicability assessment based on your profile. This will be refined during the risk assessment phase.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Control ID</TableHead>
                <TableHead>Control Name</TableHead>
                <TableHead>Initial Assessment</TableHead>
                <TableHead>Reasoning</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {draftScope.annexAAssumptions.map((assumption, i) => (
                <TableRow key={i}>
                  <TableCell className="font-mono text-sm">{assumption.controlId}</TableCell>
                  <TableCell>{assumption.controlName}</TableCell>
                  <TableCell>
                    <Badge
                      variant={
                        assumption.applicability === 'likely_applicable'
                          ? 'default'
                          : assumption.applicability === 'likely_not_applicable'
                          ? 'secondary'
                          : 'outline'
                      }
                    >
                      {assumption.applicability === 'likely_applicable'
                        ? 'Likely Applicable'
                        : assumption.applicability === 'likely_not_applicable'
                        ? 'Likely N/A'
                        : 'Needs Review'}
                    </Badge>
                  </TableCell>
                  <TableCell className="text-sm">{assumption.reasoning}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>

      {/* Risk Areas */}
      <Card>
        <CardHeader>
          <CardTitle>Identified Risk Areas</CardTitle>
          <CardDescription>
            Key areas to focus on during risk assessment based on your profile
          </CardDescription>
        </CardHeader>
        <CardContent>
          <ul className="list-disc pl-5 space-y-1">
            {draftScope.riskAreas.map((area, i) => (
              <li key={i}>{area}</li>
            ))}
          </ul>
        </CardContent>
      </Card>

      {/* Recommendations */}
      <Card>
        <CardHeader>
          <CardTitle>Recommendations</CardTitle>
          <CardDescription>
            Suggested next steps and considerations for your ISMS implementation
          </CardDescription>
        </CardHeader>
        <CardContent>
          <ul className="list-disc pl-5 space-y-1">
            {draftScope.recommendations.map((rec, i) => (
              <li key={i}>{rec}</li>
            ))}
          </ul>
        </CardContent>
      </Card>

      {/* Action buttons */}
      <div className="flex justify-between items-center pt-4">
        <div className="space-x-2">
          {readOnly ? (
            <Button variant="outline" onClick={onUpdateResponses}>
              Update Responses
            </Button>
          ) : (
            <Button variant="outline" onClick={onEdit}>
              Edit Responses
            </Button>
          )}
          <Button variant="outline" onClick={onRegenerate}>
            Regenerate
          </Button>
        </div>
        {!readOnly && (
          <Button onClick={onApprove} disabled={isApproving} size="lg">
            {isApproving ? 'Approving...' : 'Approve Scope'}
          </Button>
        )}
      </div>

      {!readOnly && (
        <p className="text-sm text-muted-foreground text-center pb-8">
          By approving this scope, you confirm you have reviewed all sections.
          An approval record will be created for audit purposes.
        </p>
      )}
    </div>
  )
}
